### ISSUE TITLE
AddSingleton list<> order

### ISSUE THREAD

**Issue by dgaspar** [davidwengier/Trains.NET#5]
https://github.com/davidwengier/Trains.NET/blob/977c1be87bd8c7375b1accb1683f89f6137cbeac/Trains.NET/Program.cs#L31

When you're scanning assemblies, will the `IBoardRenderer` items' registration ordering be deterministic?

**Comment by davidwengier** [comment]
Thanks for the question! 

No, the ordering is not deterministic and shouldn't be relied on. Even if it seems to be consistent it's not a good long term bet. See here: https://blogs.msdn.microsoft.com/ericlippert/2012/05/31/past-performance-is-no-guarantee-of-future-results/

At the moment this doesn't matter because we're just in the "drawing static things" stage but it's something that definitely needs to be addressed in future. Either we can add some smarts to the DI system to ensure the order (like an `[Order]` attribute of some kind) or we can do the same thing in the rendering code. I'm not honestly sure which is better... yet :)
